apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-defence-man-in-the-middle-attack
spec:
  selectorLabels:
      nodeSelector:
          hostname: xyz
- macro: consider_packet_socket_communication
  condition: (always_true)

- list: arp
  items: []

- rule: Packet socket created in container
  desc: Audit on network packet and ARP request IP conflict 
  condition: 
      evt.type=socket and 
      evt.arg[0]=AF_PACKET and 
      consider_packet_socket_communication and 
      container and 
      not proc.name in (user_known_packet_socket_binaries)
  output: Packet socket was created in a container 
            (user=%user.name user_loginuid=%user.loginuid //username&ID
            command=%proc.cmdline socket_info=%evt.args //socket_Network
            container_id=%container.id //Container_id 
            container_name=%container.name //Name_of_Container
            image=%container.image.repository:%container.image.tag)
  priority: NOTICE
   
  action:
    Aduit
  severity: 3